# Generated by Django 5.1.2 on 2024-11-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_post_updated_at"),
        ("comments", "0003_comment_post_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="articles.post",
            ),
        ),
    ]
