# Generated by Django 5.1.2 on 2024-11-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_alter_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="article",
        ),
    ]
