# Generated by Django 5.1.2 on 2024-11-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="edited_at",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_content",
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
