# Generated by Django 5.1.2 on 2024-11-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_rename_edited_at_post_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
