# Generated by Django 5.1.2 on 2024-11-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_post_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_name",
            new_name="author",
        ),
    ]
